### ISSUE TITLE
Errors out on npm cache clean with npm 6.2.0

### ISSUE THREAD

**Issue by doug-a-brunner** [theoy/npm-git-publish#26]
As of npm 6.2.0, cleaning a specific package from the cache is no longer supported, so I get this error out:
```
{ Error: Command failed: npm cache clean mypackage@myversion
npm ERR! npm cache clear does not accept arguments

npm ERR! A complete log of this run can be found in:
npm ERR!     path\to\npm-cache\_logs\currentdatestamp-debug.log

    at ChildProcess.exithandler (child_process.js:275:12)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Socket.stream.socket.on (internal/child_process.js:346:11)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at Pipe._handle.close [as _onclose] (net.js:567:12)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'npm cache clean mypackage@myversion' }
```

**Comment by theoy** [comment]
Thanks for the high quality bug report @doug-a-brunner, definitely looks like something we should look into (happy to take PRs too :) )
